<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>TeleCore.Research</RootNamespace>
        <AssemblyName>TeleCore.Research</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TeleCore\TeleCore.csproj"/>
    </ItemGroup>

</Project>
