<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>TeleCore.FlowCore</RootNamespace>
        <AssemblyName>TeleCore.FlowCore</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TeleCore\TeleCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Lib.Harmony" Version="2.4.2" />
      <PackageReference Update="Krafs.Publicizer" Version="2.3.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
