<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

    <!-- Basic Project Properties -->
    <PropertyGroup>
        <TargetFramework>net481</TargetFramework>
        <LangVersion>latest</LangVersion>
        <RootNamespace>TeleCore</RootNamespace>
        <AssemblyName>TeleCore</AssemblyName>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <!-- Package Metadata -->
    <PropertyGroup>
        <Title>TeleCore</Title>
        <Version>1.9.8.5</Version>
        <Authors>Telefonmast (aka Maxim)</Authors>
        <Company>Telefonmast</Company>
        <Copyright>Copyright © 2023 Maxim Switenko</Copyright>
        <Description>A collection of tools and functionalities for RimWorld modding.</Description>
        <PackageTags>RimWorld;Mod;Telefonmast;Framework;Library</PackageTags>
        <RepositoryUrl>https://github.com/RealTelefonmast/TeleCore</RepositoryUrl>
        <PackageProjectUrl>https://github.com/RealTelefonmast/TeleCore</PackageProjectUrl>
        <PackageIcon>TeleCore.jpg</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <!-- Debug Configuration -->
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <DebugType>full</DebugType>
    </PropertyGroup>

    <!-- Release Configuration -->
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DefineConstants>TRACE</DefineConstants>
        <WarningLevel>4</WarningLevel>
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
    </PropertyGroup>

    <!-- Package Files -->
    <!--
    <ItemGroup>
        <None Include="TeleCore.jpg" Pack="True" PackagePath="\" />
        <Content Include="$(SolutionDir)LICENSE.md" Pack="True" PackagePath="" Link="LICENSE.md" />
        <Content Include="$(SolutionDir)README.md" Pack="True" PackagePath="" Link="README.md" />
    </ItemGroup>
    -->

    <!-- NuGet References -->
    <ItemGroup>
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="Krafs.Rimworld.Ref" Version="1.5.4409" GeneratePathProperty="true" ExcludeAssets="runtime">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="Lib.Harmony" Version="2.3.6">
            <PrivateAssets>all</PrivateAssets>
            <ExcludeAssets>runtime</ExcludeAssets>
            <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <!-- Publicizer Settings -->
    <ItemGroup>
        <Publicize Include="Assembly-CSharp" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\TeleCore.Net.Shared\TeleCore.Net.Shared.csproj" />
    </ItemGroup>
    

</Project>