<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk" DefaultTargets="Build">

    <PropertyGroup>
        <RootNamespace>TeleCore.RimWorld.Loader</RootNamespace>
        <AssemblyName>TeleCore.RimWorld.Loader</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\TeleCore.Std\TeleCore.Std.csproj" />
    </ItemGroup>

</Project>
