<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <RootNamespace>TeleCore.Math</RootNamespace>
        <AssemblyName>TeleCore.Math</AssemblyName>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Update="Lib.Harmony" Version="2.4.2" />
      <PackageReference Update="Krafs.Publicizer" Version="2.3.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
